export const projects = [
  {
    title: "InyerM - Shop",
    description: "inyerm-shop",
    image: "InyerM-Shop.gif",
    technologies: [1, 2, 3, 5, 8, 11, 12],
    deployed: false,
    githubUrl: "https://github.com/InyerM/inyerm-shop",
  },
  {
    title: "FinanzApp",
    description: "finanz-app",
    image: "FinanzApp.gif",
    technologies: [1, 2, 3, 5, 9, 11, 12],
    deployed: false,
    githubUrl: "https://github.com/InyerM/finanz-app",
  },
  {
    title: "OpenJira",
    description: "open-jira",
    image: "OpenJira.gif",
    technologies: [1, 2, 3, 5, 8, 11, 12],
    deployed: false,
    githubUrl: "https://github.com/InyerM/open-jira",
  },
  {
    title: "PokemonStatic",
    description: "pokemon-static",
    image: "PokemonStatic.gif",
    technologies: [1, 2, 3, 5, 8],
    deployed: true,
    link: "https://pokemon-static-henna.vercel.app/",
    githubUrl: "https://github.com/InyerM/pokemon-static",
  },
  {
    title: "RickAndMorty",
    description: "rick-and-morty",
    image: "RickAndMorty.gif",
    technologies: [3, 5, 6, 7, 10],
    deployed: true,
    link: "https://sveltekit-rick-and-morty-xlj3.vercel.app/",
    githubUrl: "https://github.com/InyerM/sveltekit-rick-and-morty",
  },
  {
    title: "XKCD Comics",
    description: "xkcd-comics-app",
    image: "xkcd.gif",
    technologies: [1, 2, 3, 5, 8, 9],
    deployed: true,
    link: "https://xkcd-comics-app.vercel.app/",
    githubUrl: "https://github.com/InyerM/xkcd-app",
  },
];
